### ISSUE TITLE
Saving creates a new instance

### ISSUE THREAD

**Issue by francoismajor** [siterig/statamic-mailerlite#12]
Any time I save the config in the control panel, it adds a new Array in the config file. Which means if I reload my browser I now have two entries. Deleting entries in the control panel never deletes entries in the config, and deleting all does not delete them either. I can delete them in the config file but this is not available to my clients.

**Comment by MeMattStone** [comment]
Hi @francoismajor , out of curiosity was the addon installed when it was still on v1.1.2? (v1.1.3 was released on 22nd Feb)

**Comment by francoismajor** [comment]
No I just installed it when I wrote. March 1st I believe.

François Major

Développeur web

418-569-7314 <4185697314>
Prendre rendez-vous <https://calendly.com/francoismajor/rdv>
francoismajor.com

**Comment by MeMattStone** [comment]
Hi @francoismajor , 

I've attempted to recreate this issue on a fresh installation of Statamic by running through the following steps:

1. Install the SiteRig MailerLite addon either from the Control Panel or via composer
2. Add a `MAILERLITE_API_KEY=` entry in the `.env` file with a MailerLite (New Version) API key
3. Run `php artisan vendor:publish --tag="mailerlite-config"` to publish the configuration file
4. Log into the Control Panel and goto the MailerLite settings
5. Configure two or more forms in the MailerLite and click Save (I had 4 separate forms in my test)
6. You should now have a saved configuration at `config/mailerlite.php` (see below for my results)

```
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | MailerLite API Key
    |--------------------------------------------------------------------------
    |
    | The API key for connecting to the MailerLite API.
    |
    */

    'api_key' => env('MAILERLITE_API_KEY'),

    /*
    |--------------------------------------------------------------------------
    | Forms
    |--------------------------------------------------------------------------
    |
    | The form settings for submissions to add to your MailerLite list.
    |
    */

    'forms' => [
        [
            'id' => 'YQvHWgVB',
            'form' => 'contact_us',
            'subscriber_group' => 81735522018396030,
            'name_field' => 'full_name',
            'email_field' => 'email_address',
            'auto_split_name' => true,
            'mapped_fields' => [
                [
                    'id' => 'kM9tTkrP',
                    'subscriber_field' => 'company',
                    'mapped_form_fields' => 'organisation_name',
                ],
            ],
        ],
        [
            'id' => 'leyioz4d',
            'form' => 'contact_us_marketing_pref5',
            'subscriber_group' => 31735536491128200,
            'name_field' => 'full_name',
            'email_field' => 'email_address',
            'auto_split_name' => true,
            'marketing_optin_field' => 'marketing_preferences',
            'mapped_fields' => [
                [
                    'id' => 'leyivt0c',
                    'subscriber_field' => 'company',
                    'mapped_form_fields' => 'organisation_name',
                ],
            ],
        ],
        [
            'id' => 'leyixrtu',
            'form' => 'mailing_list',
            'subscriber_group' => 31735212859083530,
            'email_field' => 'email',
            'auto_split_name' => true,
        ],
        [
            'id' => 'leyj1x5k',
            'form' => 'sign-up_form',
            'subscriber_group' => 31735546891128600,
            'name_field' => 'first_name',
            'email_field' => 'email_address',
            'auto_split_name' => false,
            'marketing_optin_field' => 'marketing',
            'mapped_fields' => [
                [
                    'id' => 'leyj753s',
                    'subscriber_field' => 'last_name',
                    'mapped_form_fields' => 'last_name',
                ],
                [
                    'id' => 'leyj9hmn',
                    'subscriber_field' => 'job_title',
                    'mapped_form_fields' => 'job_title',
                ],
                [
                    'id' => 'leyj9ryh',
                    'subscriber_field' => 'company',
                    'mapped_form_fields' => 'company_name',
                ],
            ],
        ],
    ],

];

```

I would recommend removing the addon and deleting your MailerLite configuration file and start from step 3 above to see if you get the same result and let me know the outcome.

**Comment by francoismajor** [comment]
Reinstalled everything and tested (1.1.3) and saving no longer creates double entries. Deleting also deletes. (just realized this is the same version I initially had, so this is weird... but anyways, everything seems to work)
