### ISSUE TITLE
Does not work unless all fields exist

### ISSUE THREAD

**Issue by francoismajor** [siterig/statamic-mailerlite#13]
I've tried creating a form with a single email field and I cannot get it to work no matter what I try.

I tested with Name, email and consent and this is the only configuration I have found that works. Removing either name or consent fails and does not add subscribers to Mailerlite. (the documentation states that only the email field is required so I would expect this to be the case). (I know certain contries require a consent field but not here, and I use double opt-in on Mailerlite's side instead)

**Comment by MeMattStone** [comment]
An updated to resolve this issue will be available shortly

**Comment by MeMattStone** [comment]
This issue has been resolved in the latest release: https://github.com/siterig/statamic-mailerlite/releases/tag/v1.1.4
