### ISSUE TITLE
Subscriber Group field displays error on saved forms

### ISSUE THREAD

**Issue by MeMattStone** [siterig/statamic-mailerlite#15]
**Describe the bug**
After saving a form with a selected Subscriber Group it displays an error:

`Error: group no longer exists`

This seems to be an issue only when connected with MailerLite (New Version) and not with MailerLite Classic

**To Reproduce**
1. Setup a form in MailerLite configuration and select a Subscriber Group
2. Save the form
3. Reload the page and you will see instead of the selected option the form displays the error message

**Expected behavior**
The field should display the selected Subscriber Group name

**Screenshots**
<img width="408" alt="Screenshot 2023-03-02 at 22 59 45" src="https://user-images.githubusercontent.com/1451037/222579324-81c39b94-9cd8-4b97-9044-07e9b4f6145f.png">

**Device (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: 16.3

**Platform (please complete the following information):**
 - Statamic version: 3.4.5
 - MailerLite for Statamic version: 1.1.3
 - MailerLite type: New Version

**Comment by MeMattStone** [comment]
Update will be published shortly to resolve this bug

**Comment by mikemartin** [comment]
@MeMattStone This might be a forma issue. It looks like the group ID isn't getting wrapped in quotes.

**Comment by MeMattStone** [comment]
Resolved in v2.0.0
