### ISSUE TITLE
Add Statamic 4 Support

### ISSUE THREAD

**Issue by mikemartin** [siterig/statamic-mailerlite#22]
Could you please add Statamic 4 support?

**Comment by mikemartin** [comment]
@MeMattStone Added support with this PR: https://github.com/siterig/statamic-mailerlite/pull/23

**Comment by MeMattStone** [comment]
Hi @mikemartin , thank you for submitting the PR. Unfortunately the changes needed for compatibility with Statamic v4+ also include some breaking changes in some of the methods and functions used to interact with Statamic. I'm currently reviewing the same changes on our other add-on Bravo for Statamic [here](https://github.com/siterig/statamic-sendinblue/pull/4) which will be released this week, and I'll then be merged across those changes and adapting them for the Mailerlite add-on next week and releasing the next version

**Comment by MeMattStone** [comment]
Support added in v2.0.0

**Comment by mikemartin** [comment]
Thank you @MeMattStone!
